### ISSUE TITLE
Why do you say your model ranks 2nd on multi-scan SemanticKITTI?

### ISSUE THREAD

**Issue by lfl256** [cardwing/Codes-for-PVKD#11]
According to the leaderboard, **DRINet_PLUSPLUS** is the 2nd ranking method.

**Comment by fh1256** [comment]
What is your account on the leaderboard?

**Comment by cardwing** [comment]
It shou be "Our model ranks 2nd on the multi-scan challenge of SemanticKITTI till 2021-12-1 00:00 Pacifc Time among all published algorithms".
