### ISSUE TITLE
This codebase is almost identical to the Cylinder3D's code, so what is new?

### ISSUE THREAD

**Issue by lfl256** [cardwing/Codes-for-PVKD#12]

**Comment by cardwing** [comment]
The DDP codes and distillation codes will be provided soon. More models such as SPVCNN, SPVNAS, CENet-based range image networks will be included. The reproduced performance is much higher than the reported value. You can try the pre-trained models first.

**Comment by fh1256** [comment]
I think most people are more interested in the training code (or any tricks that you used in the training), instead of the pretrained models.

**Comment by youquanl** [comment]
I think you can fine-tune the model using the trained weight to initialize the network. I can obtain some performance gains using this training strategy. @lfl256

**Comment by bigsheep2012** [comment]
Hello @cardwing ,  May I know if the mentioned training code is released? I am still waiting for the mentioned reproduced "CENet" code in your paper. If there is no plan to release the code, plz let us know.

> The DDP codes and distillation codes will be provided soon. More models such as SPVCNN, SPVNAS, CENet-based range image networks will be included. The reproduced performance is much higher than the reported value. You can try the pre-trained models first.
