### ISSUE TITLE
Multiple GPU training on nuScenes

### ISSUE THREAD

**Issue by hlesmqh** [cardwing/Codes-for-PVKD#2]
Congratulations! I find it costs a lot of time for training with single GPU. Would you please release code for multiple GPU training? (or multiple GPU for Cylinder3D) Thank you!

**Comment by cardwing** [comment]
The Cylinder3D-DDP is under testing. We will release it soon. Stay tuned.

**Comment by cardwing** [comment]
You can refer to [this code](https://github.com/xizaoqu/Cylinder3D/blob/master/train_slurm.py) to achieve multi-gpu training.
