### ISSUE TITLE
Pointwise refinement and shuffling

### ISSUE THREAD

**Issue by L-Reichardt** [cardwing/Codes-for-PVKD#25]
Hello,

why is the data shuffled in the Cylinder feature generation? How is this shuffling considered in the pointwise refinement module (not in code, but in Paper)

Best Regards

**Comment by cardwing** [comment]
The shuffling is to make the model not to merely remember the label order (e.g., the label is 11112222xxxxx) and learn more knowledge (e.g., more general representations) from the input data. The shuffling can be tackled by the point-voxel variable.

**Comment by L-Reichardt** [comment]
@cardwing Thank you for your answer, that makes sense.

When devoxelizing the output of the voxel-net, is that output shuffled also, before going into the point-refinement net? Then reverse shuffled at the end, for a final prediction?

Or are the features of the voxel-pointnet skip-connections reverse shuffled before being added in the point-refinement net?
