### ISSUE TITLE
How many GPUs did you use

### ISSUE THREAD

**Issue by 91916117qq** [cardwing/Codes-for-PVKD#4]
Congratulations!
Sense increasing number of gpu during training equals to increasing the batch size, would you tell me how many GPUs did you use?
Besides, it's difficult to find spconv==1.2.1, would you release the spconv==1.2.1 to help me reproduce your results?

**Comment by l1997i** [comment]
I suggest you compile `spconv` 1.2.1 from official [source code](https://github.com/traveller59/spconv/tree/v1.2.1).
```bash
git clone https://github.com/traveller59/spconv.git -b v1.2.1
```
Then, following the [guide](https://github.com/traveller59/spconv/tree/v1.2.1#install-on-ubuntu-16041804) step 1 to 4.

**Comment by 91916117qq** [comment]
Thx!
What about the number of gou? In the paper batch size = 4, did you use 2 gpu for training?

**Comment by ouenal** [comment]
Why is this issue closed, the question still hangs?
