### ISSUE TITLE
pre-train model

### ISSUE THREAD

**Issue by fengjiang5** [cardwing/Codes-for-PVKD#5]
Hello, congratulations for your great work. I want to know when you train the pre-train model, did you use both the train and valid dataset?
Thanks for your reply.

**Comment by cardwing** [comment]
We first train the model using the train set and then finetune the model using both train and val set.

**Comment by fengjiang5** [comment]
> We first train the model using the train set and then finetune the model using both train and val set.

Thanks a lot for your quick reply.
